---

mysql_packages_state: present
mysql_repository: 'deb http://repo.mysql.com/apt/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} mysql-{{ mysql_version }}'

mysql_packages:
  - mysql-server
  - mysql-client

mysql_version: 5.7

mysql:
  root_password: "do not use this (old) var format for root password"

mariadb_packages_state: present
mariadb_debian_repository: 'deb https://mirrors.nxthost.com/mariadb/repo/10.2/debian stretch main'
mariadb_version: '10.2'
mariadb_packages:
  - mariadb-server
  - mariadb-client

mysql_replicate_conf_file: /etc/mysql/mariadb.conf.d/replicate-dbs.cnf
mysql_replicate_dbs: []