---
# Installs Yarn on Debian based systems.

- name: Add Yarn APT key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Add Yarn APT source
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
  register: node_yarn_repo

- name: Update APT cache
  apt:
    update_cache: yes
  when: node_yarn_repo.changed

- name: Install Yarn
  apt:
    name: yarn
    state: present
    install_recommends: no
