networks:
  app-network:
    driver: bridge
services:
  covid19-dsp-adminer:
    container_name: covid19-dsp-adminer
    image: adminer
    networks:
      app-network: null
    ports:
    - 8080:8080/tcp
    restart: unless-stopped
  covid19-dsp-app:
    build:
      context: /home/tudor/projects/covid-19-entry-dsp/docker
      dockerfile: ./../docker/Dockerfile
    container_name: covid19-dsp-app
    image: covid19_dsp/php
    networks:
      app-network: null
    restart: unless-stopped
    volumes:
    - /home/tudor/projects/covid-19-entry-dsp/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:rw
    - /home/tudor/projects/covid-19-entry-dsp:/var/www:rw
    working_dir: /var/www
  covid19-dsp-db:
    container_name: covid19-dsp-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: toor
    image: mysql:5.7.22
    networks:
      app-network: null
    ports:
    - 3306:3306/tcp
    restart: unless-stopped
    volumes:
    - /home/tudor/projects/covid-19-entry-dsp/docker/mysql/my.cnf:/etc/mysql/my.cnf:rw
    - dbdata:/var/lib/mysql:rw
  covid19-dsp-mailhog:
    container_name: covid19-dsp-mailhog
    image: mailhog/mailhog
    ports:
    - 1025:1025/tcp
    - 8025:8025/tcp
    restart: unless-stopped
  covid19-dsp-phpmyadmin:
    container_name: covid19-dsp-phpmyadmin
    depends_on:
    - covid19-dsp-db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      PMA_HOST: covid19-dsp-db
    image: phpmyadmin/phpmyadmin
    networks:
      app-network: null
    ports:
    - 8081:80/tcp
    restart: unless-stopped
  covid19-dsp-redis:
    container_name: covid19-dsp-redis
    image: redis:5.0.0-alpine
    networks:
      app-network: null
    ports:
    - 6379:6379/tcp
    restart: unless-stopped
    volumes:
    - redis-data:/data:rw
  covid19-dsp-webserver:
    container_name: covid19-dsp-webserver
    image: nginx:alpine
    networks:
      app-network: null
    ports:
    - 80:80/tcp
    - 443:443/tcp
    restart: unless-stopped
    volumes:
    - /home/tudor/projects/covid-19-entry-dsp/docker/nginx/conf.d:/etc/nginx/conf.d:rw
    - /home/tudor/projects/covid-19-entry-dsp:/var/www:rw
version: '3.0'
volumes:
  dbdata:
    driver: local
  redis-data:
    driver: local

