version: '3'
services:

  #Redis
  covid19-dsp-redis:
    image: redis:5.0.0-alpine
    container_name: covid19-dsp-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - app-network
    volumes:
      - redis-data:/data

  #Adminer
  covid19-dsp-adminer:
    image: adminer
    container_name: covid19-dsp-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

  #Phpmyadmin
  covid19-dsp-phpmyadmin:
    depends_on:
      - covid19-dsp-db
    image: phpmyadmin/phpmyadmin
    container_name: covid19-dsp-phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app-network

  #Mailhog
  covid19-dsp-mailhog:
    image: mailhog/mailhog
    container_name: covid19-dsp-mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  redis-data:
    driver: local
