---
- name: Run npm install
  shell: cd {{deploy_helper.new_release_path}} && npm install
  environment: "{{ project_environment }}"

- name: Run npm dev
  shell: cd {{deploy_helper.new_release_path}} && npm run dev
  environment: "{{ project_environment }}"

- name: Run artisan config cache
  shell: cd {{deploy_helper.new_release_path}} && php artisan config:cache
  environment: "{{ project_environment }}"

- name: Run artisan config clear
  shell: cd {{deploy_helper.new_release_path}} && php artisan config:clear
  environment: "{{ project_environment }}"

- name: Run artisan migrate
  shell: cd {{deploy_helper.new_release_path}} && php artisan migrate --force
  environment: "{{ project_environment }}"

- name: Clear the opcache
  service: name=php7.2-fpm state=restarted
  become: true

- name: Test Nginx config before restarting the service
  command: nginx -t
  become: true

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  become: true
