version: '3'
services:

  #MySQL Service
  covid19-dsp-db:
    image: mysql:5.7.22
    container_name: covid19-dsp-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: DB_DATABASE
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql/
      - ./../.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
